{% set tpl = ix_lib.base.render.Render(values) %}

{% set c1 = tpl.add_container(values.consts.c1_name, values.crowdsec.image_selector) %}

{% do c1.healthcheck.set_custom_test(["CMD", "cscli", "lapi", "status"]) %}

{% do c1.environment.add_env("COLLECTIONS", values.crowdsec.collections|join(",")) %}
{% do c1.environment.add_env("LOCAL_API_URL", "http://0.0.0.0:%d"|format(values.network.api_port.port_number)) %}
{% do c1.environment.add_env("DISABLE_LOCAL_API", false) %}
{% do c1.environment.add_user_envs(values.crowdsec.additional_envs) %}

{% do c1.add_port(values.network.api_port) %}

{% if values.crowdsec.docker_enable %}
  {% do c1.add_docker_socket(read_only=True) %}
{% endif %}

{% do c1.add_storage("/var/lib/crowdsec/data", values.storage.db) %}
{% do c1.add_storage("/etc/crowdsec", values.storage.config) %}

{% for store in values.storage.additional_storage %}
  {% do c1.add_storage(store.mount_path, store) %}
{% endfor %}

{% do tpl.portals.add(values.network.api_port) %}

{{ tpl.render() | tojson }}
