words:
  - CIFS
  - CPUS
  - dnsmasq
  - Healtcheck
  - ipaddr
  - isready
  - Jellyfin
  - logsearch
  - Mebibytes
  - minio
  - nocopy
  - tailscale
  - tailscaled
  - pihole
  - radarr
  - qbittorrent
  - Syncthing
  - tmpfs
  - tracebacklimit
  - truenas
  - userspace
