resources:
  limits:
    cpus: 2.0
    memory: 4gb

TZ: America/New_York

plex:
  claim: ""
  # plex | plexpass
  image: plex
  additional_envs: []
network:
  host_network: false
  web_port: 32400

run_as:
  user: 568
  group: 568

storage:
  data:
    type: host_path
    host_path_config:
      path: /mnt/plex-data
  config:
    type: volume
    volume_name: plex-config
  logs:
    type: volume
    volume_name: plex-logs
  transcode:
    type: tmpfs
    volume_name: plex-transcode
  additional_storage:
    - type: volume
      volume_name: plex-series
      mount_path: /plex-series
    - type: anonymous
      mount_path: /scratchpad
    - type: host_path
      mount_path: /plex-video
      host_path_config:
        path: /mnt/plex-video
