resources:
  limits:
    cpus: 2.0
    memory: 4gb

TZ: America/New_York

plex:
  claim: ""
  # plex | plexpass
  image: plex
  additional_envs: []
network:
  host_network: false
  web_port: 32400

run_as:
  user: 568
  group: 568
