name: plex
train: charts
lib_version: 1.0.0
version: 1.0.0

title: Plex
description: Plex is a media server that allows you to stream your media to any Plex client.
containerVersion: "1.40.2.8395"
home: https://plex.tv
icon: https://media.sys.truenas.net/apps/plex/icons/icon.png
categories:
  - media
screenshots:
  - https://media.sys.truenas.net/apps/plex/screenshots/screenshot1.png
  - https://media.sys.truenas.net/apps/plex/screenshots/screenshot2.png
sources:
  - https://plex.tv
  - https://hub.docker.com/r/plexinc/pms-docker
keywords:
  - plex
  - media
