{% set plex_container_name = "plex" %}
{% set plex_image = "plexinc/pms-docker:1.40.2.8395-c67dce28e" %}
{% set plex_pass_image = "plexinc/pms-docker:plexpass" %}
{% set plex_images = {
  "plex": plex_image,
  "plex_pass": plex_pass_image
} %}

{% set volumes = namespace(items={}) %}
{% set volume_mounts = namespace(items=[]) %}

{% if ix_lib.base.storage.vol(data=storage.data) %}
  {% set _ = volumes.items.update(ix_lib.base.storage.vol(data=storage.data)) %}
  {% set _ = volume_mounts.items.append(ix_lib.base.storage.vol_mount(data=dict(storage.data, **{"mount_path": "/data"}), ix_volumes=ixVolumes)) %}
{% endif %}
{% if ix_lib.base.storage.vol(data=storage.config) %}
  {% set _ = volumes.items.update(ix_lib.base.storage.vol(data=storage.config)) %}
  {% set _ = volume_mounts.items.append(ix_lib.base.storage.vol_mount(data=dict(storage.config, **{"mount_path": "/config"}), ix_volumes=ixVolumes)) %}
{% endif %}
{% if ix_lib.base.storage.vol(data=storage.logs) %}
  {% set _ = volumes.items.update(ix_lib.base.storage.vol(data=storage.logs)) %}
  {% set _ = volume_mounts.items.append(ix_lib.base.storage.vol_mount(data=dict(storage.logs, **{"mount_path": "/config/Library/Application Support/Plex Media Server/Logs"}), ix_volumes=ixVolumes)) %}
{% endif %}
{% if ix_lib.base.storage.vol(data=storage.transcode) %}
  {% set _ = volumes.items.update(ix_lib.base.storage.vol(data=storage.transcode)) %}
  {% set _ = volume_mounts.items.append(ix_lib.base.storage.vol_mount(data=dict(storage.transcode, **{"mount_path": "/transcode"}), ix_volumes=ixVolumes)) %}
{% endif %}
{% for store in storage.additional_storage %}
  {% if ix_lib.base.storage.vol(data=store) %}
    {% set _ = volumes.items.update(ix_lib.base.storage.vol(data=store)) %}
    {% set _ = volume_mounts.items.append(ix_lib.base.storage.vol_mount(data=store, ix_volumes=ixVolumes)) %}
  {% endif %}
{% endfor %}

{# Containers #}
services:
  {{ plex_container_name }}:
    user: "0:0"
    image: {{ plex_images[plex.image_selector] }}
    restart: unless-stopped
    deploy:
      resources: {{ ix_lib.base.resources.resources(resources) | tojson }}
    {% if network.host_network %}
    network_mode: host
    {% endif %}
    {% set caps = ix_lib.base.security.get_caps(add=["CHOWN", "DAC_OVERRIDE", "FOWNER", "SETGID", "SETUID", "KILL"]) %}
    cap_add: {{ caps.add | tojson }}
    cap_drop: {{ caps.drop | tojson }}
    security_opt: {{ ix_lib.base.security.get_sec_opts() | tojson }}
    {% if network.dns_opts %}
    dns_opt: {{ ix_lib.base.network.dns_opts(network.dns_opts) | tojson }}
    {% endif %}
    {% set test = "/healthcheck.sh" %}
    healthcheck: {{ ix_lib.base.healthchecks.check_health(test) | tojson }}
    environment: {{ ix_lib.base.environment.envs(app={
      "TZ": TZ,
      "PLEX_UID": run_as.user,
      "PLEX_GID": run_as.group,
      "PLEX_CLAIM": plex.claim_token,
    }, user=plex.additional_envs) | tojson }}
    {% if not network.host_network %}
    ports:
      - {{ ix_lib.base.ports.get_port(port={"target": 32400, "published": network.web_port}) | tojson }}
    {% endif %}
    volumes: {{ volume_mounts.items | tojson }}

{% if volumes.items %}
volumes: {{ volumes.items | tojson }}
{% endif %}
